### ISSUE TITLE
Cron jobs

### ISSUE THREAD

**Issue by julianxhokaxhiu** [stucki/docker-lineageos#20]
Would be awesome if you could add cronjobs support to this Docker, by customing two ENV variables:

```
CRONJOB_TIME="00 12 * * *"
DEVICE_LIST="hammerhead,bullhead"
```

This would improve a lot for example considering the usage of a nightly build.

Thank you in advance :)

**Comment by stucki** [comment]
Hmm, this will require the Docker container to run permanently. Adding a cron service also needs more under the hood changes because the container would no longer run a single process.

That saying, I don't like to add more complexity which only helps a small number of users. How about a) triggering the cronjob on the host system, or b) add this feature to your own fork?
